(function() {var implementors = {};
implementors["futures"] = ["impl&lt;R:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a> for <a class='struct' href='futures/io/struct.BufReader.html' title='futures::io::BufReader'>BufReader</a>&lt;R&gt;","impl&lt;A,&nbsp;B&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a> for <a class='struct' href='futures/io/struct.Chain.html' title='futures::io::Chain'>Chain</a>&lt;A,&nbsp;B&gt; <span class='where'>where A: <a class='trait' href='futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a>&lt;Item=<a class='enum' href='futures/io/enum.Ready.html' title='futures::io::Ready'>Ready</a>,&nbsp;Error=<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; + <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a>, B: <a class='trait' href='futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a>&lt;Item=<a class='enum' href='futures/io/enum.Ready.html' title='futures::io::Ready'>Ready</a>,&nbsp;Error=<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; + <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a></span>","impl&lt;A&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a> for <a class='struct' href='futures/io/struct.Take.html' title='futures::io::Take'>Take</a>&lt;A&gt; <span class='where'>where A: <a class='trait' href='futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a>&lt;Item=<a class='enum' href='futures/io/enum.Ready.html' title='futures::io::Ready'>Ready</a>,&nbsp;Error=<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; + <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
